codeforamerica/ohana-api

app/views/admin/programs/index.html.haml, spec/features/admin/programs/visit_programs_spec.rb
=> Hide add new program for admin without access

Gemfile, Gemfile.lock, app/controllers/admin/registrations_controller.rb, app/controllers/concerns/private_registration.rb, app/controllers/user/registrations_controller.rb, app/mailers/admin_mailer.rb, app/views/admin_mailer/existing_email_signup.html.haml, config/environments/development.rb, config/initializers/devise.rb, spec/features/admin/sign_up_spec.rb, spec/features/signup_spec.rb, spec/support/mailer_macros.rb
Devise allows user enumeration by default, but they provide a `paranoid` setting to prevent enumeration when resetting a password or resending confirmation instructions. This PR turns the `paranoid` setting on.
In addition, this PR also makes sure that enumeration is not possible during sign up. Devise does not provide a way to prevent user enumeration for the `registerable` module, so I wrote my own by overriding the `create` method in the Devise registrations controller.
So now, when you try to sign up with an existing email address, instead of getting an error message that says the email has already been taken, you get the same success notice as you would during a regular successful sign up, and an email is sent to the user letting them know that a request was made to sign up with …
=> Prevent discovery of existing email addresses

app/models/address.rb, app/models/mail_address.rb, app/validators/state_province_validator.rb, config/locales/en.yml, spec/features/admin/locations/update_address_spec.rb, spec/features/admin/locations/update_mail_address_spec.rb, spec/models/address_spec.rb, spec/models/mail_address_spec.rb, spec/rails_helper.rb
From my initial research, it looks like only the US and Canada use 2-letter abbreviations for states/provinces. If we come across any other ones, we can add them then.
=> Only validate state_province length for US and CA

app/helpers/application_helper.rb, app/views/admin/dashboard/index.html.haml, spec/features/admin/dashboard_spec.rb
The version number is based on the VERSION file from the codeforamerica/ohana-api repo. Because deployments can manage and customize their instances of Ohana API however they choose, the version number does not necessarily mean that a particular deployment is exactly in sync with the upstream repo. It should be used as a general indicator of when an update was last peformed.
The version number appears in the footer of the admin home page, and only for super admins. It also links to the ohana-api repo's Changelog to make it easy to see what has changed since a particular version.
Closes #294.
=> Display Ohana API version for super admins.

app/views/layouts/application.html.haml
This PR removes a hard-coded "San Mateo County" from the default `<meta name="description">`, replacing it with the appropriate `admin.api_location` from the locale files.
=> Make meta description more generic for different Ohana deployments

db/seeds.rb
Because we are using the letter_opener gem, every time an email gets sent, a new browser tab is opened. While testing and resetting the DB, having browser tabs open each time and steal focus from the Terminal gets annoying.
We're not testing or using emails during the seeding of the DB, so we can suppress emails by using Devise's `skip_confirmation!` method.
=> Disable email delivery during rake db:seed

app/models/address.rb, app/models/mail_address.rb, app/validators/state_province_validator.rb, spec/features/admin/locations/update_address_spec.rb, spec/features/admin/locations/update_mail_address_spec.rb, spec/models/address_spec.rb, spec/models/mail_address_spec.rb
Not all countries have states or provinces, and not all countries that have them require them in postal addresses. For now, the app only requires them for the US and Canada.
=> Conditionally validate presence of state_province

config/database.yml
The DATABASE_URL setting will be used if it is present, otherwise the existing defaults are used for development and test.
This change makes it possible for users who aren't using `localhost` for Postgres to configure their database in `config/application.yml`. For example, my Ohana databases live in a Docker container at 192.168.59.103 and require a specific username and password to access.
=> Allow DATABASE_URL to be used for any enviroment

.gitignore, .rspec, Gemfile, Gemfile.lock, app/controllers/admin/csv_controller.rb, app/helpers/admin/zip_download_helper.rb, app/jobs/zip_delete_job.rb, app/jobs/zip_download_job.rb, app/views/admin/csv/holiday_schedules.csv.shaper, app/views/admin/csv/locations.csv.shaper, app/views/admin/csv/organizations.csv.shaper, app/views/admin/csv/regular_schedules.csv.shaper, app/views/admin/csv/services.csv.shaper, app/views/admin/dashboard/index.html.haml, config/application.rb, config/locales/en.yml, config/routes.rb, lib/csv_downloader.rb, spec/controllers/admin/csv_controller_spec.rb, spec/features/admin/dashboard_spec.rb, spec/jobs/zip_delete_job_spec.rb, spec/jobs/zip_download_job_spec.rb, spec/lib/csv_downloader_spec.rb, spec/spec_helper.rb, spec/support/webmock.rb
Since large files can take a while to process, the zip file is
prepared in the background so that the user can continue browsing
the site. The background processing is provided via the Sucker Punch
gem, which doesn't require any additional Heroku dependencies such as
Redis.
While the zip file is being generated, the button on the admin
interface reads "Generating zip file", and when it's ready, it reads
"Download zip file".
Once the file has been downloaded, it is deleted from the /tmp folder
a minute later so that a new zip file can be generated at a later time.
The zip file's name contains the date at which it was downloaded to
make it easy to see when the zip was last generated.
I also cleaned up the csv.shaper files to remove duplicated cells.
Closes #326.
=> Provide one-click download of CSV files as a zip

script/setup_heroku
Was previously getting this warning when running the setup_heroku script: WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead. This commit removes the warning.
=> Update deprecated command for Heroku addons

Gemfile, Gemfile.lock, app/models/concerns/search.rb
Why:
We're only using the pg_search gem for the keyword search, and the query that it generates is not that complicated. Upgrading to the latest version of the pg_search gem breaks our tests. So, instead of having to rely on a third party, we can generate the same query ourselves using activerecord, and reduce our dependencies with the same stone.
How:
To figure out what the proper query was, I fired up the Rails console and ran `Location.keyword('food')`. That gave me the SQL query I needed, which I then converted to activerecord so that the result would return an ActiveRecord::Relation that can be chained with other scopes.
=> Replace pg_search with activerecord query

app/helpers/application_helper.rb, spec/features/admin/dashboard_spec.rb
Why:
Previously, the version test would fail intermittently on Travis because File.read would be called by something else, like a gem.
How:
Explicitly read the VERSION file in the test.
=> Make dashboard_spec more robust

app/models/concerns/search.rb, spec/api/search_spec.rb
Why:
Search queries that contain the keyword parameter are ordered by the
rank calculated by the Postgres full text search feature. In some
cases, the rank could be the same for all results, but in those cases,
Postgres does not guarantee that the order will be same all the time.
This will cause issues with pagination since the order might not be
consistent as you go from one page to another.
In order to keep the order consistent, we can specify an additional way
to rank the results. I've chosen to order by most recently updated.
=> Order results by updated_at when rank is the same

Gemfile, Gemfile.lock
Why:
To allow developers to measure the performance and memory usage of the app.
Further reading:
http://www.nateberkopec.com/2015/08/05/rack-mini-profiler-the-secret-weapon.html
https://github.com/schneems/derailed_benchmarks
=> Add gems to assist in profiling app performance

app/models/concerns/search.rb, spec/api/search/service_area_spec.rb
When performing a search, if a location has many services that match the `service_area` parameter, the same location will be duplicated in the search results.
To eliminate the duplication, you can either append `.uniq` or `.group('locations.id')` to the `Location#service_area` query. However, both are not without consequences. If the keyword parameter is also present when using `.uniq`, then we need to add a select clause that selects all location columns, as well as the full-text search rank.
If we use `group`, then we get an error when the `location` parameter is present due to the way the geocoder gem works. The issue in this case is caused by the `maximum(:updated_at)` call used in the `cache_key` method in `search_controller`. I couldn't figure out how to make `group` work, so I went …
=> Eliminate duplicates when using service_area

Gemfile, Gemfile.lock, INSTALL.md, lib/address_extractor.rb, lib/category_importer.rb, lib/category_presenter.rb, lib/contact_importer.rb, lib/entity_importer.rb, lib/file_checker.rb, lib/holiday_schedule_importer.rb, lib/location_importer.rb, lib/location_presenter.rb, lib/mail_address_importer.rb, lib/organization_importer.rb, lib/phone_importer.rb, lib/program_importer.rb, lib/regular_schedule_importer.rb, lib/service_importer.rb, lib/tasks/import.rake, spec/lib/address_extractor_spec.rb, spec/lib/category_importer_spec.rb, spec/lib/contact_importer_spec.rb, spec/lib/holiday_schedule_importer_spec.rb, spec/lib/location_importer_spec.rb, spec/lib/mail_address_importer_spec.rb, spec/lib/organization_importer_spec.rb, spec/lib/phone_importer_spec.rb, spec/lib/program_importer_spec.rb, spec/lib/regular_schedule_importer_spec.rb, spec/lib/service_importer_spec.rb
In order to dynamically update the full-text search index when
entities change, the various models include callbacks to update their
parents via `touch`. This unnecessarily slows down the import because
touching in Rails 4 has a lot of overhead. Touching is not needed
during the import. Locations can be updated separately after the
import.
To bypass the touching, Rails provides a `no_touching` method, which
is what I've used here. It significantly sped up the import of a
medium-sized dataset from 31 minutes to 11 minutes.
The import script was also consuming more memory than necessary
because it was reading the CSV files with `File.read`, then loading
the contents in an array with `CVS.new.entries`.
The `File.read` part is not necessary since you can pass in a path
directly to `CSV.new` …
=> Optimize import with no_touching and SmarterCSV

app/controllers/api/v1/status_controller.rb, config/environments/production.rb, script/setup_heroku, spec/requests/status_spec.rb
**Why**:
Mandrill is getting rid of their free Heroku add-on. SendGrid still has a free plan as of today.
Closes #372
=> Replace Mandrill with SendGrid

Gemfile, Gemfile.lock, app/controllers/admin/registrations_controller.rb, app/controllers/user/registrations_controller.rb, app/models/admin.rb, app/models/user.rb
The `test_after_commit` gem is needed to test Devise confirmation
emails, which are now sent via the `after_commit` callback.
See this note in the Devise CHANGELOG:
https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#410
=> Update Devise to 4.1.1

app/controllers/application_controller.rb
**Why**: To protect the admin interface from CSRF attacks.
=> Protect from forgery with exception

spec/spec_helper.rb
**Why**: To make it easy to run only the tests that failed in the last run.
=> Add support for RSpec’s only-failures mode

spec/api/get_locations_spec.rb, spec/api/get_organization_locations_spec.rb
**Why**: These specs represent functionality that was removed a long time ago. Mail address and contacts are no longer part of the JSON when the API returns a list of locations. They are only included when viewing an individual location.
=> Remove pending serialization specs

spec/features/admin/dashboard_spec.rb
**Why**: some `have_link` expectations were missing the `href:`.
=> Fix Capybara warnings

README.md
**Why**: We never renewed the domain registration, and someone else bought it.
=> Remove link to ohanapi.org from README

config/initializers/geocoder.rb
When using Ohana's default settings for the `geocoder` gem in a Heroku deployment, it is really easy to hit Google's rate limit. This is due to the fact that there is a small pool of outbound IP addresses used by Heroku dynos and Google's rate limiting in the absence of an API key is IP address based.
This PR configures the `http_proxy` setting for the `geocoder` library to use the QuotaGuard service if `ENV['QUOTAGUARD_URL']` is present. If it is not present, this PR doesn't affect existing behavior. The use of the QuotaGuard Heroku addon with Rails is documented here: https://devcenter.heroku.com/articles/quotaguard#using-with-rails
Since Ohana's documentation for geocoder configuration lives in the wiki, I can update the wiki if this PR is accepted.
=> Use QuotaGuard to avoid geocoder rate limits

config/initializers/devise.rb, script/setup_heroku
This PR updates the `setup_heroku` script with the following improvements:
1. Stop provisioning `DEVISE_SECRET_KEY` since a separate setting for Devise is not needed with modern versions of Devise and Rails 4+ (cf. https://github.com/plataformatec/devise/pull/2835). The `devise.rb` initializer has been updated to allow the application to start without `ENV['DEVISE_SECRET_KEY']`, in which case Devise will use `Rails.application.config.secret_key_base` (controlled by `ENV['SECRET_TOKEN']`)
2. Allow the script to be run idempotently
* Check if a Heroku add-on is installed before calling `heroku addons:create`
* Check if `SECRET_TOKEN` is set before generating one
3. Use Ruby instead of Python for UUID generation, since this is a Ruby-based project
4. Add `quotaguard:starter` addon (cf. #415)
=> Update setup_heroku script

config/environments/development.rb
**Why**: When assets are first being compiled, there is no request and the app will throw an exception because the call to AssetHosts.new only includes one argument instead of two. Specifying an asset host is not required in development.
=> Don’t set asset host in development

spec/features/admin/contacts/delete_contact_spec.rb, spec/features/admin/locations/delete_location_spec.rb, spec/features/admin/organizations/delete_contact_spec.rb, spec/features/admin/organizations/delete_organization_spec.rb, spec/features/admin/programs/delete_program_spec.rb, spec/features/admin/services/delete_contact_spec.rb, spec/features/admin/services/delete_service_spec.rb
**Why**: There have been some random failures in Circle CI, and they all seem to be for JS deletion specs. Increasing the wait time should fix this. Ideally, instead of checking the current path, we would look for content on the page, which will automatically use the default wait time, which is currently set to 10 seconds.
=> Increase wait time for deletion specs

Procfile
**Why**: To allow migrations to run automatically when deploying to Heroku, and to ensure that the build does not get deployed if the migration fails.
Reference: https://devcenter.heroku.com/articles/release-phase
=> Add DB migration release phase to Procfile

app/controllers/application_controller.rb
**Why**: In Rails 5, files outside `app` are no longer autoloaded after booting in the production environment.
=> Require default_host in ApplicationController

.foreman.example, .gitignore, bin/setup
**Why**: The release phase that was added recently doesn’t work in development and prevents the app from running with `foreman start`. One solution is to add a `.foreman` file that only applies locally (and is therefore gitignored) that tells Foreman to run without the release phase.
=> Add .foreman to allow ‘foreman start’ locally

.reek, lib/asset_hosts.rb, spec/lib/asset_hosts_spec.rb
**Why**: In Rails 5.1, the request is not always supplied, for example when precompiling assets.
Reference: http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html
=> Make AssetHosts request argument optional

.circleci/config.yml
**Why**: To keep things DRY and consistent
=> Use config instead of env vars in Circle CI

config/application.example.yml, config/initializers/geocoder.rb
**Why**: It is required by Google.
=> Require Google API key option in geocoding config

.reek.yml, app/models/location.rb, spec/factories/locations.rb
**Why**: In order to determine whether an admin user is able to edit
a particular location, their email address is compared to the list of
admin_emails associated with the location. When an admin account is
created, the email is automatically converted to lowercase. However,
when an admin email is added to a location, it does not get converted.
The current comparison looks for an exact match. To fix this issue, we
can either fix the comparison to be case insensitive, or automatically
convert admin emails to lowercase. The latter is the simplest
solution, and is what I implemented here.
=> Downcase admin_emails before saving
